# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.setWindowModality(QtCore.Qt.ApplicationModal)
        Preferences.resize(910, 733)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Preferences.sizePolicy().hasHeightForWidth())
        Preferences.setSizePolicy(sizePolicy)
        Preferences.setMinimumSize(QtCore.QSize(910, 733))
        Preferences.setMaximumSize(QtCore.QSize(910, 733))
        Preferences.setBaseSize(QtCore.QSize(910, 780))
        Preferences.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(Preferences)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 160, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 160, 121, 16))
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(20, 190, 411, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_2.setPalette(palette)
        self.widget_2.setAutoFillBackground(True)
        self.widget_2.setObjectName("widget_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_3.setGeometry(QtCore.QRect(340, 90, 61, 24))
        self.spinBox_3.setFrame(False)
        self.spinBox_3.setMaximum(127)
        self.spinBox_3.setProperty("value", 44)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_2.setGeometry(QtCore.QRect(340, 50, 61, 24))
        self.spinBox_2.setFrame(False)
        self.spinBox_2.setMaximum(127)
        self.spinBox_2.setProperty("value", 38)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 59, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 59, 16))
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox.setGeometry(QtCore.QRect(340, 10, 61, 24))
        self.spinBox.setAcceptDrops(False)
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(False)
        self.spinBox.setMaximum(127)
        self.spinBox.setProperty("value", 36)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 59, 16))
        self.label.setObjectName("label")
        self.button_Slider_1 = QtWidgets.QSlider(self.widget_2)
        self.button_Slider_1.setGeometry(QtCore.QRect(150, 10, 160, 22))
        self.button_Slider_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_Slider_1.setMouseTracking(False)
        self.button_Slider_1.setMaximum(127)
        self.button_Slider_1.setProperty("value", 36)
        self.button_Slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.button_Slider_1.setObjectName("button_Slider_1")
        self.button_Slider_2 = QtWidgets.QSlider(self.widget_2)
        self.button_Slider_2.setGeometry(QtCore.QRect(150, 50, 160, 22))
        self.button_Slider_2.setMaximum(127)
        self.button_Slider_2.setProperty("value", 38)
        self.button_Slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.button_Slider_2.setObjectName("button_Slider_2")
        self.button_Slider_3 = QtWidgets.QSlider(self.widget_2)
        self.button_Slider_3.setGeometry(QtCore.QRect(150, 90, 160, 22))
        self.button_Slider_3.setMaximum(127)
        self.button_Slider_3.setProperty("value", 44)
        self.button_Slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.button_Slider_3.setObjectName("button_Slider_3")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(490, 190, 401, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_3.setPalette(palette)
        self.widget_3.setAutoFillBackground(True)
        self.widget_3.setObjectName("widget_3")
        self.Smooth_label = QtWidgets.QLabel(self.widget_3)
        self.Smooth_label.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.Smooth_label.setObjectName("Smooth_label")
        self.Smooth_Slider = QtWidgets.QSlider(self.widget_3)
        self.Smooth_Slider.setGeometry(QtCore.QRect(140, 90, 160, 22))
        self.Smooth_Slider.setMouseTracking(True)
        self.Smooth_Slider.setTabletTracking(True)
        self.Smooth_Slider.setMaximum(5)
        self.Smooth_Slider.setProperty("value", 0)
        self.Smooth_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Smooth_Slider.setObjectName("Smooth_Slider")
        self.Distance_min_label = QtWidgets.QLabel(self.widget_3)
        self.Distance_min_label.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.Distance_min_label.setObjectName("Distance_min_label")
        self.Distance_min_Slider = QtWidgets.QSlider(self.widget_3)
        self.Distance_min_Slider.setGeometry(QtCore.QRect(140, 10, 160, 22))
        self.Distance_min_Slider.setMouseTracking(True)
        self.Distance_min_Slider.setTabletTracking(True)
        self.Distance_min_Slider.setMaximum(2000)
        self.Distance_min_Slider.setSingleStep(1)
        self.Distance_min_Slider.setProperty("value", 150)
        self.Distance_min_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Distance_min_Slider.setObjectName("Distance_min_Slider")
        self.Distance_max_Slider = QtWidgets.QSlider(self.widget_3)
        self.Distance_max_Slider.setGeometry(QtCore.QRect(140, 50, 160, 22))
        self.Distance_max_Slider.setMouseTracking(True)
        self.Distance_max_Slider.setTabletTracking(True)
        self.Distance_max_Slider.setMaximum(2500)
        self.Distance_max_Slider.setProperty("value", 1200)
        self.Distance_max_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Distance_max_Slider.setObjectName("Distance_max_Slider")
        self.Distance_max_label = QtWidgets.QLabel(self.widget_3)
        self.Distance_max_label.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.Distance_max_label.setObjectName("Distance_max_label")
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_6.setGeometry(QtCore.QRect(330, 90, 61, 24))
        self.spinBox_6.setFrame(False)
        self.spinBox_6.setMaximum(5)
        self.spinBox_6.setProperty("value", 0)
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_10 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_10.setGeometry(QtCore.QRect(330, 10, 61, 24))
        self.spinBox_10.setFrame(False)
        self.spinBox_10.setMaximum(2500)
        self.spinBox_10.setProperty("value", 150)
        self.spinBox_10.setObjectName("spinBox_10")
        self.spinBox_11 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_11.setGeometry(QtCore.QRect(330, 50, 61, 24))
        self.spinBox_11.setFrame(False)
        self.spinBox_11.setMaximum(2500)
        self.spinBox_11.setProperty("value", 1200)
        self.spinBox_11.setObjectName("spinBox_11")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(20, 510, 411, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_4.setPalette(palette)
        self.widget_4.setAutoFillBackground(True)
        self.widget_4.setObjectName("widget_4")
        self.spinBox_8 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_8.setGeometry(QtCore.QRect(340, 50, 61, 24))
        self.spinBox_8.setFrame(False)
        self.spinBox_8.setProperty("value", 10)
        self.spinBox_8.setObjectName("spinBox_8")
        self.spinBox_7 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_7.setGeometry(QtCore.QRect(340, 10, 61, 24))
        self.spinBox_7.setFrame(False)
        self.spinBox_7.setMinimum(1)
        self.spinBox_7.setMaximum(16)
        self.spinBox_7.setProperty("value", 1)
        self.spinBox_7.setObjectName("spinBox_7")
        self.Latency_label = QtWidgets.QLabel(self.widget_4)
        self.Latency_label.setGeometry(QtCore.QRect(10, 50, 59, 16))
        self.Latency_label.setObjectName("Latency_label")
        self.MIDI_Channel_Slider = QtWidgets.QSlider(self.widget_4)
        self.MIDI_Channel_Slider.setGeometry(QtCore.QRect(150, 10, 160, 22))
        self.MIDI_Channel_Slider.setMinimum(1)
        self.MIDI_Channel_Slider.setMaximum(16)
        self.MIDI_Channel_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.MIDI_Channel_Slider.setObjectName("MIDI_Channel_Slider")
        self.MIDI_Channel_label = QtWidgets.QLabel(self.widget_4)
        self.MIDI_Channel_label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.MIDI_Channel_label.setObjectName("MIDI_Channel_label")
        self.Latency_Slider = QtWidgets.QSlider(self.widget_4)
        self.Latency_Slider.setGeometry(QtCore.QRect(150, 50, 160, 22))
        self.Latency_Slider.setMinimum(5)
        self.Latency_Slider.setMaximum(30)
        self.Latency_Slider.setProperty("value", 10)
        self.Latency_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Latency_Slider.setObjectName("Latency_Slider")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 350, 411, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_5.setGeometry(QtCore.QRect(340, 11, 61, 24))
        self.spinBox_5.setFrame(False)
        self.spinBox_5.setMaximum(127)
        self.spinBox_5.setProperty("value", 31)
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(10, 11, 121, 20))
        self.label_10.setObjectName("label_10")
        self.Pot_Left_Slider = QtWidgets.QSlider(self.widget)
        self.Pot_Left_Slider.setGeometry(QtCore.QRect(150, 11, 160, 22))
        self.Pot_Left_Slider.setMaximum(127)
        self.Pot_Left_Slider.setProperty("value", 11)
        self.Pot_Left_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Pot_Left_Slider.setObjectName("Pot_Left_Slider")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(10, 47, 131, 31))
        self.label_13.setObjectName("label_13")
        self.Pot_Right_Slider = QtWidgets.QSlider(self.widget)
        self.Pot_Right_Slider.setGeometry(QtCore.QRect(150, 51, 160, 22))
        self.Pot_Right_Slider.setMaximum(127)
        self.Pot_Right_Slider.setProperty("value", 42)
        self.Pot_Right_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Pot_Right_Slider.setObjectName("Pot_Right_Slider")
        self.spinBox_9 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_9.setGeometry(QtCore.QRect(340, 51, 61, 24))
        self.spinBox_9.setFrame(False)
        self.spinBox_9.setMaximum(127)
        self.spinBox_9.setProperty("value", 42)
        self.spinBox_9.setObjectName("spinBox_9")
        self.SS_Slider = QtWidgets.QSlider(self.widget)
        self.SS_Slider.setGeometry(QtCore.QRect(150, 91, 160, 22))
        self.SS_Slider.setMaximum(127)
        self.SS_Slider.setProperty("value", 11)
        self.SS_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.SS_Slider.setObjectName("SS_Slider")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(10, 87, 121, 31))
        self.label_11.setObjectName("label_11")
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_4.setGeometry(QtCore.QRect(340, 90, 61, 24))
        self.spinBox_4.setFrame(False)
        self.spinBox_4.setMaximum(127)
        self.spinBox_4.setProperty("value", 11)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(150, -20, 181, 21))
        self.label_14.setObjectName("label_14")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(20, 20, 871, 131))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_5.setPalette(palette)
        self.widget_5.setAutoFillBackground(True)
        self.widget_5.setObjectName("widget_5")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(70, 30, 41, 16))
        self.label_6.setObjectName("label_6")
        self.Connect = QtWidgets.QPushButton(self.widget_5)
        self.Connect.setGeometry(QtCore.QRect(170, 90, 113, 35))
        self.Connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Connect.setStatusTip("")
        self.Connect.setWhatsThis("")
        self.Connect.setObjectName("Connect")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setGeometry(QtCore.QRect(210, 10, 31, 21))
        self.label_8.setObjectName("label_8")
        self.Login = QtWidgets.QLineEdit(self.widget_5)
        self.Login.setGeometry(QtCore.QRect(170, 30, 113, 21))
        self.Login.setFrame(False)
        self.Login.setObjectName("Login")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setGeometry(QtCore.QRect(70, 60, 59, 16))
        self.label_7.setObjectName("label_7")
        self.Password = QtWidgets.QLineEdit(self.widget_5)
        self.Password.setGeometry(QtCore.QRect(170, 60, 113, 21))
        self.Password.setAutoFillBackground(True)
        self.Password.setFrame(False)
        self.Password.setObjectName("Password")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(640, 30, 113, 21))
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setGeometry(QtCore.QRect(580, 40, 21, 21))
        self.label_9.setObjectName("label_9")
        self.label_20 = QtWidgets.QLabel(self.widget_5)
        self.label_20.setGeometry(QtCore.QRect(580, 60, 31, 21))
        self.label_20.setObjectName("label_20")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(640, 60, 113, 21))
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_22 = QtWidgets.QLabel(self.widget_5)
        self.label_22.setGeometry(QtCore.QRect(660, 10, 61, 20))
        self.label_22.setObjectName("label_22")
        self.Get_IP = QtWidgets.QPushButton(self.widget_5)
        self.Get_IP.setGeometry(QtCore.QRect(640, 90, 113, 35))
        self.Get_IP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Get_IP.setWhatsThis("")
        self.Get_IP.setObjectName("Get_IP")
        self.WiFi_is_Con = QtWidgets.QLabel(self.widget_5)
        self.WiFi_is_Con.setGeometry(QtCore.QRect(390, 70, 141, 20))
        self.WiFi_is_Con.setAutoFillBackground(False)
        self.WiFi_is_Con.setObjectName("WiFi_is_Con")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(490, 350, 401, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_6.setPalette(palette)
        self.widget_6.setAutoFillBackground(True)
        self.widget_6.setObjectName("widget_6")
        self.spinBox_14 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_14.setGeometry(QtCore.QRect(330, 90, 61, 24))
        self.spinBox_14.setFrame(False)
        self.spinBox_14.setMaximum(127)
        self.spinBox_14.setProperty("value", 127)
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_12 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_12.setGeometry(QtCore.QRect(330, 10, 61, 24))
        self.spinBox_12.setFrame(False)
        self.spinBox_12.setMinimum(1)
        self.spinBox_12.setMaximum(8)
        self.spinBox_12.setProperty("value", 1)
        self.spinBox_12.setObjectName("spinBox_12")
        self.label_17 = QtWidgets.QLabel(self.widget_6)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.label_17.setObjectName("label_17")
        self.spinBox_13 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_13.setGeometry(QtCore.QRect(330, 50, 61, 24))
        self.spinBox_13.setFrame(False)
        self.spinBox_13.setMaximum(50)
        self.spinBox_13.setProperty("value", 1)
        self.spinBox_13.setObjectName("spinBox_13")
        self.LED_Speed_Slider = QtWidgets.QSlider(self.widget_6)
        self.LED_Speed_Slider.setGeometry(QtCore.QRect(140, 50, 160, 22))
        self.LED_Speed_Slider.setMaximum(50)
        self.LED_Speed_Slider.setProperty("value", 1)
        self.LED_Speed_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.LED_Speed_Slider.setObjectName("LED_Speed_Slider")
        self.LED_Bright_Slider = QtWidgets.QSlider(self.widget_6)
        self.LED_Bright_Slider.setGeometry(QtCore.QRect(140, 90, 160, 22))
        self.LED_Bright_Slider.setMaximum(127)
        self.LED_Bright_Slider.setProperty("value", 127)
        self.LED_Bright_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.LED_Bright_Slider.setObjectName("LED_Bright_Slider")
        self.label_16 = QtWidgets.QLabel(self.widget_6)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.widget_6)
        self.label_18.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_18.setObjectName("label_18")
        self.LED_Prog_Slider = QtWidgets.QSlider(self.widget_6)
        self.LED_Prog_Slider.setGeometry(QtCore.QRect(140, 10, 160, 22))
        self.LED_Prog_Slider.setMinimum(1)
        self.LED_Prog_Slider.setMaximum(8)
        self.LED_Prog_Slider.setProperty("value", 1)
        self.LED_Prog_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.LED_Prog_Slider.setObjectName("LED_Prog_Slider")
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(490, 510, 401, 58))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_7.setPalette(palette)
        self.widget_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_7.setMouseTracking(False)
        self.widget_7.setAutoFillBackground(True)
        self.widget_7.setObjectName("widget_7")
        self.Buttons = QtWidgets.QPushButton(self.widget_7)
        self.Buttons.setGeometry(QtCore.QRect(270, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Buttons.setPalette(palette)
        self.Buttons.setWhatsThis("")
        self.Buttons.setCheckable(True)
        self.Buttons.setChecked(True)
        self.Buttons.setFlat(False)
        self.Buttons.setObjectName("Buttons")
        self.SuperSonic = QtWidgets.QPushButton(self.widget_7)
        self.SuperSonic.setGeometry(QtCore.QRect(10, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 241, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 156, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 241, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 156, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 241, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 156, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 235, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.SuperSonic.setPalette(palette)
        self.SuperSonic.setStatusTip("")
        self.SuperSonic.setWhatsThis("")
        self.SuperSonic.setAutoFillBackground(False)
        self.SuperSonic.setCheckable(True)
        self.SuperSonic.setChecked(True)
        self.SuperSonic.setFlat(False)
        self.SuperSonic.setObjectName("SuperSonic")
        self.Potentiometrs = QtWidgets.QPushButton(self.widget_7)
        self.Potentiometrs.setGeometry(QtCore.QRect(140, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Potentiometrs.setPalette(palette)
        self.Potentiometrs.setWhatsThis("")
        self.Potentiometrs.setCheckable(True)
        self.Potentiometrs.setChecked(True)
        self.Potentiometrs.setFlat(False)
        self.Potentiometrs.setObjectName("Potentiometrs")
        self.COM_Ports = QtWidgets.QLabel(self.centralwidget)
        self.COM_Ports.setGeometry(QtCore.QRect(370, 40, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 22, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 22, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.COM_Ports.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.COM_Ports.setFont(font)
        self.COM_Ports.setObjectName("COM_Ports")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(490, 610, 401, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_8.setPalette(palette)
        self.widget_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_8.setWhatsThis("")
        self.widget_8.setAutoFillBackground(True)
        self.widget_8.setObjectName("widget_8")
        self.Store = QtWidgets.QPushButton(self.widget_8)
        self.Store.setGeometry(QtCore.QRect(10, 50, 181, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Store.setPalette(palette)
        self.Store.setWhatsThis("")
        self.Store.setDefault(False)
        self.Store.setFlat(False)
        self.Store.setObjectName("Store")
        self.Button_Save = QtWidgets.QPushButton(self.widget_8)
        self.Button_Save.setGeometry(QtCore.QRect(270, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Button_Save.setPalette(palette)
        self.Button_Save.setWhatsThis("")
        self.Button_Save.setDefault(False)
        self.Button_Save.setFlat(False)
        self.Button_Save.setObjectName("Button_Save")
        self.Load_Preset = QtWidgets.QPushButton(self.widget_8)
        self.Load_Preset.setGeometry(QtCore.QRect(10, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Load_Preset.setPalette(palette)
        self.Load_Preset.setWhatsThis("")
        self.Load_Preset.setDefault(False)
        self.Load_Preset.setFlat(False)
        self.Load_Preset.setObjectName("Load_Preset")
        self.Quit = QtWidgets.QPushButton(self.widget_8)
        self.Quit.setGeometry(QtCore.QRect(210, 50, 181, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Quit.setPalette(palette)
        self.Quit.setWhatsThis("")
        self.Quit.setDefault(False)
        self.Quit.setFlat(False)
        self.Quit.setObjectName("Quit")
        self.Save_Preset = QtWidgets.QPushButton(self.widget_8)
        self.Save_Preset.setGeometry(QtCore.QRect(140, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Save_Preset.setPalette(palette)
        self.Save_Preset.setWhatsThis("")
        self.Save_Preset.setDefault(False)
        self.Save_Preset.setFlat(False)
        self.Save_Preset.setObjectName("Save_Preset")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(180, 320, 151, 21))
        self.label_21.setObjectName("label_21")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(640, 480, 111, 20))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(170, 480, 181, 21))
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(660, 320, 81, 21))
        self.label_19.setObjectName("label_19")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(20, 670, 411, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_9.setPalette(palette)
        self.widget_9.setAutoFillBackground(True)
        self.widget_9.setObjectName("widget_9")
        self.label_25 = QtWidgets.QLabel(self.widget_9)
        self.label_25.setGeometry(QtCore.QRect(110, 0, 181, 16))
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(650, 580, 71, 20))
        self.label_24.setObjectName("label_24")
        self.widget_12 = QtWidgets.QWidget(self.centralwidget)
        self.widget_12.setGeometry(QtCore.QRect(20, 610, 411, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_12.setPalette(palette)
        self.widget_12.setAutoFillBackground(True)
        self.widget_12.setObjectName("widget_12")
        self.Load_Param_Progress = QtWidgets.QProgressBar(self.widget_12)
        self.Load_Param_Progress.setGeometry(QtCore.QRect(147, 14, 161, 16))
        self.Load_Param_Progress.setProperty("value", 24)
        self.Load_Param_Progress.setObjectName("Load_Param_Progress")
        self.Load_Param = QtWidgets.QLabel(self.widget_12)
        self.Load_Param.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.Load_Param.setAutoFillBackground(False)
        self.Load_Param.setObjectName("Load_Param")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 650, 411, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 690, 411, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        Preferences.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Preferences)
        self.statusbar.setObjectName("statusbar")
        Preferences.setStatusBar(self.statusbar)
        self.actionControllers_Setup = QtWidgets.QAction(Preferences)
        self.actionControllers_Setup.setObjectName("actionControllers_Setup")

        self.retranslateUi(Preferences)
        self.button_Slider_1.valueChanged['int'].connect(self.spinBox.setValue)
        self.button_Slider_2.valueChanged['int'].connect(self.spinBox_2.setValue)
        self.button_Slider_3.valueChanged['int'].connect(self.spinBox_3.setValue)
        self.Smooth_Slider.valueChanged['int'].connect(self.spinBox_6.setValue)
        self.MIDI_Channel_Slider.valueChanged['int'].connect(self.spinBox_7.setValue)
        self.Latency_Slider.valueChanged['int'].connect(self.spinBox_8.setValue)
        self.Pot_Left_Slider.valueChanged['int'].connect(self.spinBox_5.setValue)
        self.Pot_Right_Slider.valueChanged['int'].connect(self.spinBox_9.setValue)
        self.SS_Slider.valueChanged['int'].connect(self.spinBox_4.setValue)
        self.LED_Prog_Slider.valueChanged['int'].connect(self.spinBox_12.setValue)
        self.LED_Speed_Slider.valueChanged['int'].connect(self.spinBox_13.setValue)
        self.LED_Bright_Slider.valueChanged['int'].connect(self.spinBox_14.setValue)
        self.spinBox.valueChanged['int'].connect(self.button_Slider_1.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.button_Slider_2.setValue)
        self.spinBox_3.valueChanged['int'].connect(self.button_Slider_3.setValue)
        self.spinBox_7.valueChanged['int'].connect(self.MIDI_Channel_Slider.setValue)
        self.spinBox_8.valueChanged['int'].connect(self.Latency_Slider.setValue)
        self.spinBox_6.valueChanged['int'].connect(self.Smooth_Slider.setValue)
        self.spinBox_5.valueChanged['int'].connect(self.Pot_Left_Slider.setValue)
        self.spinBox_9.valueChanged['int'].connect(self.Pot_Right_Slider.setValue)
        self.spinBox_4.valueChanged['int'].connect(self.SS_Slider.setValue)
        self.spinBox_12.valueChanged['int'].connect(self.LED_Prog_Slider.setValue)
        self.spinBox_13.valueChanged['int'].connect(self.LED_Speed_Slider.setValue)
        self.spinBox_14.valueChanged['int'].connect(self.LED_Bright_Slider.setValue)
        self.Connect.clicked.connect(self.widget_5.show)
        self.Login.textChanged['QString'].connect(self.widget_5.show)
        self.Password.textChanged['QString'].connect(self.widget_5.show)
        self.SuperSonic.toggled['bool'].connect(self.widget_7.show)
        self.Potentiometrs.toggled['bool'].connect(self.widget_7.show)
        self.Buttons.toggled['bool'].connect(self.widget_7.show)
        self.Get_IP.clicked.connect(self.lineEdit_3.clear)
        self.Get_IP.clicked.connect(self.lineEdit_4.clear)
        self.spinBox_10.valueChanged['int'].connect(self.Distance_min_Slider.setValue)
        self.Distance_min_Slider.valueChanged['int'].connect(self.spinBox_10.setValue)
        self.Distance_max_Slider.valueChanged['int'].connect(self.spinBox_11.setValue)
        self.spinBox_11.valueChanged['int'].connect(self.Distance_max_Slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.Login, self.Password)
        Preferences.setTabOrder(self.Password, self.Connect)
        Preferences.setTabOrder(self.Connect, self.lineEdit_3)
        Preferences.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Preferences.setTabOrder(self.lineEdit_4, self.Get_IP)
        Preferences.setTabOrder(self.Get_IP, self.button_Slider_1)
        Preferences.setTabOrder(self.button_Slider_1, self.spinBox)
        Preferences.setTabOrder(self.spinBox, self.button_Slider_2)
        Preferences.setTabOrder(self.button_Slider_2, self.spinBox_2)
        Preferences.setTabOrder(self.spinBox_2, self.button_Slider_3)
        Preferences.setTabOrder(self.button_Slider_3, self.spinBox_3)
        Preferences.setTabOrder(self.spinBox_3, self.Pot_Left_Slider)
        Preferences.setTabOrder(self.Pot_Left_Slider, self.spinBox_5)
        Preferences.setTabOrder(self.spinBox_5, self.Pot_Right_Slider)
        Preferences.setTabOrder(self.Pot_Right_Slider, self.spinBox_9)
        Preferences.setTabOrder(self.spinBox_9, self.SS_Slider)
        Preferences.setTabOrder(self.SS_Slider, self.spinBox_4)
        Preferences.setTabOrder(self.spinBox_4, self.SuperSonic)
        Preferences.setTabOrder(self.SuperSonic, self.Potentiometrs)
        Preferences.setTabOrder(self.Potentiometrs, self.Buttons)
        Preferences.setTabOrder(self.Buttons, self.Distance_min_Slider)
        Preferences.setTabOrder(self.Distance_min_Slider, self.spinBox_10)
        Preferences.setTabOrder(self.spinBox_10, self.Distance_max_Slider)
        Preferences.setTabOrder(self.Distance_max_Slider, self.spinBox_11)
        Preferences.setTabOrder(self.spinBox_11, self.Smooth_Slider)
        Preferences.setTabOrder(self.Smooth_Slider, self.spinBox_6)
        Preferences.setTabOrder(self.spinBox_6, self.MIDI_Channel_Slider)
        Preferences.setTabOrder(self.MIDI_Channel_Slider, self.spinBox_7)
        Preferences.setTabOrder(self.spinBox_7, self.Latency_Slider)
        Preferences.setTabOrder(self.Latency_Slider, self.spinBox_8)
        Preferences.setTabOrder(self.spinBox_8, self.LED_Prog_Slider)
        Preferences.setTabOrder(self.LED_Prog_Slider, self.spinBox_12)
        Preferences.setTabOrder(self.spinBox_12, self.LED_Speed_Slider)
        Preferences.setTabOrder(self.LED_Speed_Slider, self.spinBox_13)
        Preferences.setTabOrder(self.spinBox_13, self.LED_Bright_Slider)
        Preferences.setTabOrder(self.LED_Bright_Slider, self.spinBox_14)
        Preferences.setTabOrder(self.spinBox_14, self.Button_Save)
        Preferences.setTabOrder(self.Button_Save, self.Load_Preset)
        Preferences.setTabOrder(self.Load_Preset, self.Store)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "CONTROL T1"))
        self.label_2.setText(_translate("Preferences", "Buttons Note Shift"))
        self.label_5.setText(_translate("Preferences", "Super Sonic Sensor"))
        self.label_3.setText(_translate("Preferences", "Button 2"))
        self.label_4.setText(_translate("Preferences", "Button 3"))
        self.label.setText(_translate("Preferences", "Button 1 "))
        self.Smooth_label.setText(_translate("Preferences", "Smoothing"))
        self.Distance_min_label.setText(_translate("Preferences", "Distance Min"))
        self.Distance_max_label.setText(_translate("Preferences", "Distance Max"))
        self.Latency_label.setText(_translate("Preferences", "Latency"))
        self.MIDI_Channel_label.setText(_translate("Preferences", "MIDI Channel"))
        self.label_10.setText(_translate("Preferences", "Potentiometer Left"))
        self.label_13.setText(_translate("Preferences", "Potentiometer Right"))
        self.label_11.setText(_translate("Preferences", "Super Sonic Sensor"))
        self.label_14.setText(_translate("Preferences", "MIDI Control Change Number"))
        self.label_6.setText(_translate("Preferences", "Login"))
        self.Connect.setText(_translate("Preferences", "Connect"))
        self.label_8.setText(_translate("Preferences", "WiFi"))
        self.label_7.setText(_translate("Preferences", "Password"))
        self.label_9.setText(_translate("Preferences", "IP"))
        self.label_20.setText(_translate("Preferences", "Port"))
        self.label_22.setText(_translate("Preferences", "DEVICE IP"))
        self.Get_IP.setText(_translate("Preferences", "Get IP"))
        self.WiFi_is_Con.setText(_translate("Preferences", "WiFi  Connected"))
        self.label_17.setText(_translate("Preferences", "Speed"))
        self.label_16.setText(_translate("Preferences", "LED Programm"))
        self.label_18.setText(_translate("Preferences", "Brightness"))
        self.Buttons.setText(_translate("Preferences", "Buttons"))
        self.SuperSonic.setText(_translate("Preferences", "Super Sonic"))
        self.Potentiometrs.setText(_translate("Preferences", "Potentiometers"))
        self.COM_Ports.setText(_translate("Preferences", "CONTROL T1"))
        self.Store.setText(_translate("Preferences", "Save"))
        self.Button_Save.setText(_translate("Preferences", "Refresh"))
        self.Load_Preset.setText(_translate("Preferences", "Load Preset"))
        self.Quit.setText(_translate("Preferences", "Quit"))
        self.Save_Preset.setText(_translate("Preferences", "Save Preset"))
        self.label_21.setText(_translate("Preferences", "MIDI Controller Number"))
        self.label_12.setText(_translate("Preferences", "Devices ON/OFF"))
        self.label_15.setText(_translate("Preferences", "MIDI Channel & Latency"))
        self.label_19.setText(_translate("Preferences", "LED Control"))
        self.label_25.setText(_translate("Preferences", "Designed by Sasha Malkovich"))
        self.label_24.setText(_translate("Preferences", "Operations"))
        self.Load_Param.setText(_translate("Preferences", "Loading Parametres"))
        self.actionControllers_Setup.setText(_translate("Preferences", "Controllers Setup"))
